"""
Django settings for aurexbuilders project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv



## imports for unfold
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Load environment variables from .env file
load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!b6up!qq3!@95n_hclva6*%x@!o2o$8w&g@1&c5_*$t0#h19$c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# ALLOWED_HOSTS = ['*']
ALLOWED_HOSTS = ['82.112.226.176','admin.aurex.accoladesweb.com','72.60.102.54','backend.aurexbuilders.com']


# Application definition

INSTALLED_APPS = [
    "ckeditor",           # ✅ REQUIRED
    'unfold',  
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_yasg',
    'general',
    'projects',
    'gallery',
    'careers',
    'leads',
    "corsheaders",
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
 
]

ROOT_URLCONF = 'aurexbuilders.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),  
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aurexbuilders.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import os
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# PostgreSQL for production
DATABASES = {
    "default": {
        "ENGINE": os.getenv("DB_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.getenv("DB_NAME", os.path.join(BASE_DIR, "db.sqlite3")),
        "USER": os.getenv("DB_USER", ""),
        "PASSWORD": os.getenv("DB_PASSWORD", ""),
        "HOST": os.getenv("DB_HOST", ""),
        "PORT": os.getenv("DB_PORT", ""),
        }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CSRF_TRUSTED_ORIGINS = [
    "https://admin.aurex.accoladesweb.com",
    "https://backend.aurexbuilders.com",    
    "http://127.0.0.1:8000",
    "http://localhost:8000",
    "https://aurex.accoladesweb.com",
    "https://aurexbuilders.com",
    "https://www.aurexbuilders.com/"    
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://localhost:3000",
    "https://aurex.accoladesweb.com",
    "https://aurexbuilders.com",
    "https://www.aurexbuilders.com"
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = os.getenv('EMAIL_BACKEND')
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = 587
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = True

UNFOLD = {
    "SITE_TITLE": "Aurex Buiilder Admin",  # Updated Title
    "SITE_HEADER": "Aurex Buiilder Admin",  # Sidebar Header
        
    # Updated Logos
        "SITE_ICON": lambda request: static("branding/logo.png"),  
        "SITE_LOGO": lambda request: static("branding/logo.png"),  

# "TABS": [
#         {
#             "models": ["university.program"],  # replace with actual app_label.model_name
#             "items": program_tabs_by_university,
#         },
#     ],
    "SIDEBAR": {
        "show_search": True,
        
          },
    "LIST_DISPLAY_HEADER_ACTIONS": False, 

    # Color scheme
    "COLORS": {
    "base": {
        "50": "249 250 251",
        "100": "243 244 246",
        "200": "220 220 220", 
        "300": "200 200 200",  
        "400": "156 163 175",
        "500": "107 114 128",
        "600": "75 85 99",
        "700": "50 50 50", 
        "800": "30 30 30", 
        "900": "20 20 20", 
        "950": "10 10 10",  
    },
    "primary": {
    "50":  "249 240 230",
    "100": "242 222 198",
    "200": "232 201 162",
    "300": "220 176 122",
    "400": "203 150 92",
    "500": "181 124 66",   # #B57C42 (main brand color)
    "600": "163 108 56",
    "700": "138 90 46",
    "800": "112 72 37",
    "900": "92 58 30",
    "950": "60 38 20",
},

    "font": {
        "subtle-light": "var(--color-base-500)",  
        "subtle-dark": "var(--color-base-400)",  
        "default-light": "var(--color-base-600)", 
        "default-dark": "var(--color-base-300)", 
        "important-light": "var(--color-base-900)",  
        "important-dark": "var(--color-base-100)",  
    },
    
},
}